### ISSUE TITLE
Question: Support yakkety

### ISSUE THREAD

**Issue by timsueberkrueb** [tjyrinki/qt57#1]
Hey, I tried using the qt57 cloud part on yakkety, but snapcraft fails because some packages listed in `build-packages` seem to no longer exist on 16.10. 
```
Could not find a required package in 'build-packages': "The cache has no package named 'libpng12-dev'"
...
RuntimeError: Error downloading stage packages for part 'qt57': no such package 'libicu55'
```
I know this is experimental, but is there any way this could be made to work on yakkety?
Thanks for your work!

**Comment by tjyrinki** [comment]
Hey! Yes, that's unfortunately the case right now. I'd hope for a solution from snapcraft side that allows for optional dependencies, but currently there'd need to be separate cloud parts for xenial/yakkety for at least the ever-changing libicuXX and libpng libraries.

Right now I'm on a long leave myself but if the snapcraft doesn't get any suitable feature soon we could eventually have something like qt57-xenial / qt57-yakkety.

**Comment by timsueberkrueb** [comment]
@tjyrinki I see, thanks very much for the information.
Is it possible to have local `after` part modules (e.g. including other `snapcraft.yaml`'s) or would I have to include the complete qt57 config in my main `snapcraft.yaml` as a part and tweak it for yakkety for now?

**Comment by keshavbhatt** [comment]
am getting this error with this part 
Issue while loading plugin: properties failed to load for qt57: ['-release', '-confirm-license', '-opensource', '-plugin-sql-mysql', '-plugin-sql-odbc', '-plugin-sql-psql', '-plugin-sql-sqlite', '-no-sql-sqlite2', '-plugin-sql-tds', '-system-sqlite', '-platform', 'linux-g++-64', '-system-harfbuzz', '-system-zlib', '-system-libpng', '-system-libjpeg', '-openssl', '-no-rpath', '-verbose', '-optimized-qmake', '-dbus-linked', '-strip', '-qpa', 'xcb', '-xcb', '-glib', '-icu', '-accessibility', '-no-compile-examples', '-no-directfb', '-gstreamer', '1.0', '-opengl', 'desktop', '-nomake', 'examples', '-nomake', 'tests', '-skip', 'qtquick1', '-skip', 'qtwayland', '-skip', 'qtwebengine', '-skip', 'qtwebview', '-skip', 'qtwebkit', '-skip', 'qtwebkit-examples'] has non-unique elements
Traceback (most recent call last):

**Comment by tjyrinki** [comment]
Hi, sorry, I'm still on vacation until Jan 2nd.

1. For yakkety problem, yes copy paste and change libpng and libicu

2. For non-unique elements, please copy the parts/plugins from this repo to your directory for now.

**Comment by timsueberkrueb** [comment]
@tjyrinki thank you, enjoy your vacation!

**Comment by tjyrinki** [comment]
I believe this should be working now - I workarounded the problem by finding packages with unchanging names that depend on the libraries needed. Waste of space is minimal and now it should work on all Ubuntu versions.
